### PR TITLE
 Don't output errors when checking for python-virtualenv on apt-based distros

### PR DESCRIPTION
**Pull request by acabal**

### CODE REVIEW

**Comment by acabal** [comment]
Should close #35

**Comment by kuba** [comment]
Unfortunately this PR will only try `virtualenv` when `python-virtualenv` cannot be found. In most recent distros there are two packages `virtualenv` and `python-virtualenv` and we want the former - with the `virtualenv` binary. Error that you experienced in #35 is for missing `virtualenv` package...

I'm not sure about `apt-cache` either.

**Comment by acabal** [comment]
OK, I switched it so it checks for virtualenv first.  But I don't think it matters so much, since python-virtualenv is just what Ubuntu 14.04 calls the virtualenv package.  Same package, different name.

What are you not sure about re. apt-cache?  We're already using apt-get, apt-cache is part of the same toolset.

**Comment by kuba** [comment]
Thanks for the PR. I made some nitpick changes, pushing to master...

**Pull request merged**
